#pragma once
//´íÎóÂë
# define ERROR_CANT_OPEN_FILE 0
# define ERROR_OUT_OF_SPACE 1
# define ERROR_INVALID_FILENAME 2
# define ERROR_NO_PERMISSION 3
# define ERROR_INVALID_PATH 4
# define ERROR_USER_NOT_EXIST 5
# define ERROR_USER_REGISTER 6
# define ERROT_OUT_OF_RANGE 7
# define ERROR_PASSWORD_WRONG 8